x-s3-env: &s3-env
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: password
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  S3_ENDPOINT: http://minio:9000
  S3_PATH_STYLE_ACCESS: "true"

services:

  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    networks:
      ice-net:
        aliases:
          - warehouse.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - minio-data:/data


  create-bucket:
    image: minio/mc

    depends_on:
      minio:
        condition: service_healthy

    networks:
      ice-net:

    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password)
      do
        echo 'waiting for minio...' && sleep 1;
      done;

      /usr/bin/mc mb minio/warehouse --ignore-existing;
      /usr/bin/mc policy set public minio/warehouse;
      exit 0;
      "


  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    networks:
      ice-net:
    ports:
      - "8080:8080"   # Spark Master web UI
      - "7077:7077"   # Spark Master port
      - "4040:4040"   # Spark application UI
    environment:
      SPARK_MODE: master
      <<: *s3-env

    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - spark-data:/opt/spark/work-dir

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-1
    networks:
      ice-net:
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      <<: *s3-env
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-2
    networks:
      ice-net:
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      <<: *s3-env
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir

  spark-worker-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-3
    networks:
      ice-net:
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      <<: *s3-env

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir


  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio

    networks:
      ice-net:

    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"

    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9047"]
      interval: 30s
      timeout: 10s
      retries: 5
    
    volumes:
      - dremio-data:/opt/dremio/data


  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile

    container_name: superset
    networks:
       ice-net:
    ports:
      - "8088:8088"

    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@superset.com
      ADMIN_PASSWORD: admin

      SUPERSET_SECRET_KEY: "pmFmur1eluMiQDoZA+cGHhY/cA8+0+Ko7EZi5afhXWlH1oH/rQkVHNVOY1hRXAUi"

      TALISMAN_ENABLED: "False"

    volumes:
      - superset-data:/app/superset_home


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: demo
    networks:
       ice-net:
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always


  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie

    networks:
      ice-net:

    ports:
      - "19120:19120"

    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/demo
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: 1234

      NESSIE_VERSION_STORE_TYPE: JDBC
      QUARKUS_LOG_LEVEL: INFO
      QUARKUS_LOG_CONSOLE_FORMAT: '%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n'

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v2/config"]
      interval: 30s
      timeout: 10s
      retries: 5

    depends_on:
      postgres:
        condition: service_healthy


networks:
     ice-net:


volumes:
     spark-data:
     minio-data:
     postgres-db-volume:
     superset-data:
     dremio-data:

   